--- 
- 
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
  

      - name: install packages
        apt:
          name: "{{ item }}"
          state: present
        loop:
           - python3-pip
           - python3-setuptools
           - python3-dev
           - libjpeg-dev
           - libopenjp2-7-dev
   


      - name: install python packages
        pip:
          name: "{{ item }}"
          executable: pip3
        loop:
           - Pillow

      - name: Delete content & directory
        file:
          state: absent
          path: /home/pi/git_scratch

      #git clone https://github.com/adafruit/Adafruit_Python_SSD1306.git
      - name: Get recusb repo from GitHub
        git: 
          dest: /home/pi/git_scratch
          repo: "https://github.com/adafruit/Adafruit_Python_SSD1306.git"
          update: yes
          force: yes
          #version: "main"

      - name: Copy OLED library from git_scratch to Adafruit_Python_SSD1306
        copy:
          src: /home/pi/Tools/scratch
          dest: /home/pi/Adafruit_Python_SSD1306
          owner: pi
          group: pi
          mode: 0775

      #cd Adafruit_Python_SSD1306
      #sudo python3 setup.py install
      - name: Execute the script
        command: sh /home/pi/Adafruit_Python_SSD1306/setup.py install

      - name: Set I2C Port
        lineinfile:
          path: /etc/modules
          line: 'i2c-dev'
