--- 
- 
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
  

      - name: install packages
        apt:
          name: "{{ item }}"
          state: present
        loop:
           - libopenjp2-7-dev


      - name: install python packages
        pip:
          name: "{{ item }}"
          executable: pip3
        loop:
           - Pillow
           - luma.oled

         # actual command in the github
         # sudo -H pip3 install --upgrade  
         # https://github.com/rm-hull/luma.oled

      - name: Download foo.conf
        get_url:
          url: "{{ item }}"
          dest: /home/pi/test
          mode: '0440'
        loop:
           - https://www.1001fonts.com/download/font/monospace.medium.ttf
           - https://github.com/rm-hull/luma.examples/blob/master/examples/demo_opts.py

      - name: Set I2C Port
        blockinfile:
          dest: "/etc/modules"
          block: |
           i2c-dev
           i2c-bcm2708


      - name: Set I2C Port part 2
        blockinfile:
          dest: "/boot/config.txt"
          block: |
           dtparam=i2c_arm=on
           dtparam=i2c1=on

